#!/usr/bin/env python3

import math
import rospy

from nav_msgs.msg import Path, Odometry
from geometry_msgs.msg import Twist
from tf.transformations import euler_from_quaternion


class PathFollowerNode(object):
    def __init__(self):
        """
        Task 6 node:
        This node receives the optimized waypoint path from Task 5 and commands
        the TurtleBot3 to drive through each waypoint.

        Subscribes to:
            /astar/waypoints  -> optimized waypoint path from Task 5
            /odom             -> robot position and orientation

        Publishes to:
            /cmd_vel          -> velocity command sent to TurtleBot3
        """

        rospy.init_node("path_follower_node")

        # Publisher used to command the robot's linear and angular velocity.
        self.cmd_vel_pub = rospy.Publisher("/cmd_vel", Twist, queue_size=10)

        # Subscriber for the optimized waypoint path generated by astar_planner.py.
        self.path_sub = rospy.Subscriber("/astar/waypoints", Path, self.path_callback)

        # Subscriber for odometry so we know where the robot currently is.
        self.odom_sub = rospy.Subscriber("/odom", Odometry, self.odom_callback)

        # Current robot pose from odometry.
        self.x = 0.0
        self.y = 0.0
        self.theta = 0.0
        self.have_odom = False

        # List of waypoint coordinates as [(x1, y1), (x2, y2), ...].
        self.waypoints = []

        # Index of the waypoint the robot is currently trying to reach.
        self.current_index = 0

        # This flag becomes True when a waypoint path is received.
        self.following_path = False

        # Distance threshold for saying the robot has reached a waypoint.
        self.distance_tolerance = rospy.get_param("~distance_tolerance", 0.12)

        # Angular threshold for deciding whether to turn first before driving.
        self.angle_tolerance = rospy.get_param("~angle_tolerance", 0.12)

        # Controller gains.
        # Higher gains make the robot respond more aggressively.
        self.linear_gain = rospy.get_param("~linear_gain", 0.25)
        self.angular_gain = rospy.get_param("~angular_gain", 1.2)

        # Safety speed limits.
        # Keep these low for the physical TurtleBot.
        self.max_linear_speed = rospy.get_param("~max_linear_speed", 0.12)
        self.max_angular_speed = rospy.get_param("~max_angular_speed", 0.6)

        # Main control loop rate.
        self.control_rate = rospy.Rate(10)

        rospy.loginfo("Path follower node started.")
        rospy.loginfo("Waiting for /astar/waypoints and /odom.")

    def path_callback(self, msg):
        """
        Callback for /astar/waypoints.

        This receives the optimized waypoint path from Task 5.
        The incoming message is nav_msgs/Path, which contains a list of PoseStamped messages.
        We extract only the x and y positions from each pose.
        """

        self.waypoints = []

        for pose_stamped in msg.poses:
            x = pose_stamped.pose.position.x
            y = pose_stamped.pose.position.y
            self.waypoints.append((x, y))

        # Start following from the first waypoint.
        self.current_index = 0

        # If no waypoints were received, do not move.
        if len(self.waypoints) == 0:
            rospy.logwarn("Received empty waypoint path.")
            self.following_path = False
            self.stop_robot()
            return

        # Turn on path following.
        self.following_path = True

        rospy.loginfo("Received waypoint path with %d waypoints.", len(self.waypoints))
        rospy.loginfo("Starting path following.")

    def odom_callback(self, msg):
        """
        Callback for /odom.

        This updates the robot's current x, y, and heading angle theta.
        The heading angle is extracted from the odometry quaternion.
        """

        self.x = msg.pose.pose.position.x
        self.y = msg.pose.pose.position.y

        # Convert quaternion orientation to roll, pitch, yaw.
        q = msg.pose.pose.orientation
        quat = [q.x, q.y, q.z, q.w]
        _, _, yaw = euler_from_quaternion(quat)

        self.theta = yaw
        self.have_odom = True

    def normalize_angle(self, angle):
        """
        Keeps an angle between -pi and +pi.

        This prevents the robot from turning the long way around.
        """

        while angle > math.pi:
            angle -= 2.0 * math.pi

        while angle < -math.pi:
            angle += 2.0 * math.pi

        return angle

    def clamp(self, value, min_value, max_value):
        """
        Limits a value between a minimum and maximum.

        Used to prevent the robot from moving too fast.
        """

        return max(min(value, max_value), min_value)

    def stop_robot(self):
        """
        Publishes a zero Twist message to stop the robot.
        """

        cmd = Twist()
        self.cmd_vel_pub.publish(cmd)

    def run(self):
        """
        Main control loop.

        The robot repeatedly:
        1. Checks if it has odometry.
        2. Checks if it has a waypoint path.
        3. Selects the current waypoint.
        4. Turns toward the waypoint.
        5. Drives toward it.
        6. Moves on to the next waypoint when close enough.
        """

        while not rospy.is_shutdown():

            # Do nothing until odometry is available.
            if not self.have_odom:
                self.control_rate.sleep()
                continue

            # Do nothing until a waypoint path has been received.
            if not self.following_path:
                self.control_rate.sleep()
                continue

            # If all waypoints are complete, stop the robot.
            if self.current_index >= len(self.waypoints):
                rospy.loginfo("Finished all waypoints.")
                self.following_path = False
                self.stop_robot()
                self.control_rate.sleep()
                continue

            # Current target waypoint.
            goal_x, goal_y = self.waypoints[self.current_index]

            # Difference between current robot position and target waypoint.
            dx = goal_x - self.x
            dy = goal_y - self.y

            # Distance from robot to current waypoint.
            distance = math.sqrt(dx * dx + dy * dy)

            # Desired heading angle toward the waypoint.
            desired_theta = math.atan2(dy, dx)

            # Difference between desired heading and robot's current heading.
            angle_error = self.normalize_angle(desired_theta - self.theta)

            # If the robot is close enough to the current waypoint,
            # move on to the next waypoint.
            if distance < self.distance_tolerance:
                rospy.loginfo(
                    "Reached waypoint %d/%d: x=%.3f y=%.3f",
                    self.current_index + 1,
                    len(self.waypoints),
                    goal_x,
                    goal_y
                )

                self.current_index += 1
                self.stop_robot()
                self.control_rate.sleep()
                continue

            # Create the velocity command.
            cmd = Twist()

            # If the robot is not facing the waypoint, rotate first.
            if abs(angle_error) > self.angle_tolerance:
                cmd.linear.x = 0.0
                cmd.angular.z = self.clamp(
                    self.angular_gain * angle_error,
                    -self.max_angular_speed,
                    self.max_angular_speed
                )

            # If the robot is mostly facing the waypoint, drive forward
            # while still correcting the heading.
            else:
                cmd.linear.x = self.clamp(
                    self.linear_gain * distance,
                    0.0,
                    self.max_linear_speed
                )

                cmd.angular.z = self.clamp(
                    self.angular_gain * angle_error,
                    -self.max_angular_speed,
                    self.max_angular_speed
                )

            # Send command to the TurtleBot.
            self.cmd_vel_pub.publish(cmd)

            # Sleep to maintain control loop rate.
            self.control_rate.sleep()


if __name__ == "__main__":
    try:
        node = PathFollowerNode()
        node.run()
    except rospy.ROSInterruptException:
        pass
